### ISSUE TITLE
Project environment specification

### ISSUE THREAD

**Issue by bkamins** [JuliaAcademy/DataScience#1]
This is a great tutorial. I would recommend one small thing for you to consider to ensure a smooth student experience.

You could consider adding Project.toml and Manifest.toml to your repository, so that you are sure that the students work on the same environment setup as you have. In particular the first notebook will not work without warnings under DataFrames 0.21.0 (current release) + soon `CSV.read` will get deprecated from CSV.jl AFAIK (therefore using `CSV.File` and then using `DataFrame` constructor on it is recommended).

**Comment by nassarhuda** [comment]
Thanks for pointing this out!

I just added the toml files. I'll double check later and test that all notebooks are working correctly under this environment. Will close this issue then.

**Comment by bkamins** [comment]
I have just checked that https://github.com/JuliaAcademy/DataScience/blob/master/Project.toml currently contains only Plots.jl, and you seem to use many more packages in the tutorial.

**Comment by nassarhuda** [comment]
My bad. These were my "test" toml files and didn't realize that I uploaded the wrong ones. I changed them earlier today. Feel free to double check and see if things look good on your end.

**Comment by bkamins** [comment]
Looks good! Thank you.

(I stress this so much as my teaching experience is that problems with dependencies is a major issue for students).

**Comment by nassarhuda** [comment]
Thanks again for bringing it up! Will close this issue for now.
