### ISSUE TITLE
softmax option not recognized in VS code

### ISSUE THREAD

**Issue by NicolasL-S** [JuliaAcademy/DataScience#10]
I can run the whole (very nice) tutorial fine in Julia REPL. But using VS code 1.46.0 with Julia 1.4.2, when I run this line

```
m = Chain(Dense(28^2, 32, relu), Dense(32, 10), softmax)
```

I get this output:

```
ERROR: UndefVarError: softmax not defined
Stacktrace:
 [1] top-level scope at REPL[119]:1
caused by [exception 10]
IOError: symlink: operation not permitted (EPERM)
Stacktrace:
... 
```
(the stack trace is very long, I could paste it if it helps.)

However, the following line works fine
```
m = Chain(Dense(28^2, 32, relu), Dense(32, 10))
```
I then block at the actual training because of the missing softmax option I presume.

**Comment by nassarhuda** [comment]
Do you mind double checking which Flux version you're using?

**Comment by NicolasL-S** [comment]
I've installed it yesterday. It is v 0.10.4.

**Comment by NicolasL-S** [comment]
Ok never mind I just tried it again and it started working fine. Hard to know what was the problem. Thanks for the very prompt reply!
