### ISSUE TITLE
Error in csv lecture

### ISSUE THREAD

**Issue by lucasfreitas1988** [JuliaAcademy/DataScience#12]
Error in line 5 of Notebook 1 (Data): 

;head programminglanguages.csv

returns

IOError: could not spawn `head programming_languages.csv`: no such file or directory (ENOENT)

what's up? I can't read a CSV file, not even on the terminal

**Comment by KmanT** [comment]
What operating system are you using? I don't think you can use `head` as command in windows.

If you cannot load the original csv file, then you need to change the file to `programminglanguages.csv` from `programming_languages.csv`. There's an extra underscore inside the notebook.

**Comment by Redmusk888** [comment]
> What operating system are you using? I don't think you can use `head` as command in windows.
> 
> If you cannot load the original csv file, then you need to change the file to `programminglanguages.csv` from `programming_languages.csv`. There's an extra underscore inside the notebook.

Instead of use `head` as command in the windows , what word i can use in the windows?

**Comment by logankilpatrick** [comment]
Updated the notebooks, thanks for pointing this out.
