### ISSUE TITLE
Extra packages needed to work with images in notebook 02

### ISSUE THREAD

**Issue by agarie** [JuliaAcademy/DataScience#13]
Hi! I'm running the notebooks to get acquainted with Julia syntax and found a few (possibly) missing dependencies. In notebook 02, when we start working with images, I had to add the packages:

- `ImageIO`
- `QuartzImageIO`
- `ImageMagick`

I'm on macOS 10.14.6 running Julia 1.4.2 installed via Homebrew. So I guess it's probably a good idea to add them to `Project.toml`?

**Comment by logankilpatrick** [comment]
Hm, I just ran this on Julia 1.6 with macOS and did not need those, if this continues to be an issue, please ping me!
