### ISSUE TITLE
Unable to open notebooks in nteract

### ISSUE THREAD

**Issue by frantisek901** [JuliaAcademy/DataScience#15]
At Julia Academy we are recommended to use nteract for using nteract notebooks. The notebooks downloaded from gitHub directly do not work for the course "Introduction to Julia" and the same holds true for this course "Data science" - I tried notebooks 1--4 and 12 and all failed to open. And the error is same for both courses and all notebooks downloaded directly from gitHub:

"Fetch content failed
SyntaxError: Unexpected token < in JSON at position 5"

this is the message I receive after try to open notebook, the page is completely blank, nothing reveals, just this message in pop-up window in upper-right corner.

I t seems as systematic error... The notebooks downloaded directly from Julia Academy page for the Julia Intro course work well, their gitHub mirror not. And I am not the one with this problem. 

So, what does we do wrong? Do we download notebooks from gitHub in wrong manner? (I download them via right-click and then save-as, not via cloning the repo) Why directly offered notebooks work and github not?

**Comment by frantisek901** [comment]
p.s. I just have cloned DataScience repo to my hard drive and the problem is still same...
Which kind of software do you use for opening *.ipynb notebooks?

**Comment by frantisek901** [comment]
P.S.S. Now I cloned repo of Bogumil Kaminski's repo "Data Frames" and his notebooks work well with nteract! I also test to download same file from github repo directly and this does not work. But "Data Science" notebooks do not work even when cloned.

**Comment by logankilpatrick** [comment]
Hm, this is likely an issue with Nteract I'm guessing. I just cloned the repo down and opened the first notebook with no issues at all.

**Comment by logankilpatrick** [comment]
Closing this for now, but please ping me if you run into more issues!
