### ISSUE TITLE
01. Data  IOError: could not spawn `wget  ...

### ISSUE THREAD

**Issue by rleyvasal** [JuliaAcademy/DataScience#16]
Notebook  **01. Data** shows the following error when running command                   ;wget "https://raw.githubusercontent.com/nassarhuda/easy_data/master/programming_languages.csv"

IOError: could not spawn `wget https://raw.githubusercontent.com/nassarhuda/easy_data/master/programming_languages.csv`: no such file or directory (ENOENT)

Running:
JuliaPro_v1.5.1-1
Windows 10 Pro 64-bit

**Comment by mahsanghani** [comment]
`download("https://raw.githubusercontent.com/nassarhuda/easy_data/master/programming_languages.csv",
    "programminglanguages.csv")` works but `;wget` does not

**Comment by Redmusk888** [comment]
I don't why this happend and how to fix it.

IOError: could not spawn `head programminglanguages.csv`: no such file or directory (ENOENT)

Running:
Julia v1.6.1 on jupyternote
Windows 10 64-bit

**Comment by logankilpatrick** [comment]
I removed this from the notebook so we should be good now!
