### ISSUE TITLE
Broken Manifest and Project

### ISSUE THREAD

**Issue by masonhargrave** [JuliaAcademy/DataScience#18]
Manifest and Project cause the Julia kernel to crash in Jupyter Notebooks.

Here is the error:
```
ERROR: LoadError: ArgumentError: Package ZeroMQ_jll does not have JLLWrappers in its dependencies:
- If you have ZeroMQ_jll checked out for development and have
  added JLLWrappers as a dependency but haven't updated your primary
  environment's manifest file, try Pkg.resolve().
- Otherwise you may need to report an issue with ZeroMQ_jll
```

This isn't me but I had the same problem (I had this problem with the 1.4.2 and 1.0.4 kernels and this person had this error with the 1.5.2 kernel):
https://discourse.julialang.org/t/package-zeromq-jll-does-not-have-jllwrappers-in-its-dependencies/48807

EDIT: Problem fixed by deleting the files Manifest and Project.

**Comment by blongworth** [comment]
Same. Should `Manifest.toml` and `Project.toml` be removed or modified? I'm not enough of a Julia person to know.

**Comment by logankilpatrick** [comment]
Updated both of them!
