### ISSUE TITLE
boxplot gives error for statistics plot

### ISSUE THREAD

**Issue by arisliang** [JuliaAcademy/DataScience#20]
https://juliaacademy.com/courses/937702/lectures/17339512

`boxplot(["eruption length"], eruptions, legend=false, size=(200,400), whisker_width=1, ylabel="time in minutes")`

gives:
> Expects 1 elements in each col of y, found 272.

**Comment by shaksham95** [comment]
The following change did the trick for me:

```
boxplot(eruptions, xlabel="eruption_length", legend=false, size=(200, 400), whisker_width=1, ylabel="ti
me in minutes")
```

**Comment by logankilpatrick** [comment]
Just updated the notebook, this should be resolved!
