### ISSUE TITLE
glmnet(X[trainids,:], y[trainids]) is ambiguous for classification notebook

### ISSUE THREAD

**Issue by arisliang** [JuliaAcademy/DataScience#22]
`path = glmnet(X[trainids, :], y[trainids])` in classification notebook 6 https://github.com/JuliaAcademy/DataScience/blob/master/06.%20Classification.ipynb

gives error:

>MethodError: glmnet(::Array{Float64,2}, ::Array{Int64,1}) is ambiguous. Candidates:
  glmnet(X::Array{Float64,2}, y; kw...) in GLMNet at C:\Users\ly\.julia\packages\GLMNet\1uQom\src\Multinomial.jl:191
  glmnet(X::AbstractArray{T,2} where T, y::AbstractArray{var"#s77",1} where var"#s77"<:Number) in GLMNet at C:\Users\ly\.julia\packages\GLMNet\1uQom\src\GLMNet.jl:492
Possible fix, define
  glmnet(::Array{Float64,2}, ::AbstractArray{var"#s77",1} where var"#s77"<:Number)
Stacktrace:
 [1] top-level scope at In[30]:2
 [2] include_string(::Function, ::Module, ::String, ::String) at .\loading.jl:1091
>

**Comment by logankilpatrick** [comment]
Just updated the notebook, this should be resolved!
