### ISSUE TITLE
[Error] Clustering Algorithms

### ISSUE THREAD

**Issue by shaksham95** [JuliaAcademy/DataScience#25]
Hey,

While trying to code along with the clustering video, I am facing issues in the following clustering methods.

**K-medoids:**

```
x_matrix = Matrix(X)
D = pairwise(Euclidean(), x_matrix, x_matrix, dims=2)
```

```
k_medoids = kmedoids(D, 10)
insertcols!(houses_data, 3, :medoids_clusters => k_medoids.assignments)
```

Error:
![image](https://user-images.githubusercontent.com/7498849/102588626-c473e800-4133-11eb-9cf3-a53939167903.png)

**Hierarchical Clustering:**

```
hier_model = hclust(distances)
L = cutree(hier_model; k=10) ## tries to form a clustering tree
insertcols!(houses_data, 3, :hierarchial_clusters => L)
```

Error:
![image](https://user-images.githubusercontent.com/7498849/102588850-187ecc80-4134-11eb-88ba-f2254ae35353.png)

Can anyone please help me with this?

**Comment by logankilpatrick** [comment]
Just updated the notebook, should be good now!
