### ISSUE TITLE
[404 NOT FOUND] Neural Networks

### ISSUE THREAD

**Issue by shaksham95** [JuliaAcademy/DataScience#26]
Hey,

While trying to load the MNIST dataset using `MNIST.images()`, I am getting the following error:

![image](https://user-images.githubusercontent.com/7498849/102688893-0712ee80-4220-11eb-9078-680e46b3a873.png)

Furthermore, after clicking on the link mentioned in the stack trace ([here](yann.lecun.com/exdb/mnist/train-images-idx3-ubyte.gz%60,)), the following page is displayed.

![image](https://user-images.githubusercontent.com/7498849/102688918-3de90480-4220-11eb-9905-e2633a9e91b9.png)

Looks like the link being used in Julia is broken. Can you please help here?

**Comment by logankilpatrick** [comment]
This has been fixed, thanks for reporting!
