### ISSUE TITLE
[Violin Plot] Issue while using the "side" keyword

### ISSUE THREAD

**Issue by shaksham95** [JuliaAcademy/DataScience#27]
Hey,

In Video 13, I am facing issues while trying to plot the violin plots side by side using the `side` keyword. Below is the code that I am using:

```
## data: 2020-02
ca = CA_df[!,Symbol("2020-02")]
ny = NY_df[!,Symbol("2020-02")]
fl = FL_df[!,Symbol("2020-02")]

## plot
violin(ny, legend=true, alpha=0.8, label="New York", side=:left)
violin!(ca, alpha=0.8, label="California", side=:left)
violin!(fl, alpha=0.8, label="Florida", side=:left)

## data: 2010-02
ny = NY_df[!, Symbol("2010-02")]
ca = CA_df[!, Symbol("2010-02")]
fl = FL_df[!, Symbol("2010-02")]

## plot
violin!(ny, legend=false, alpha=0.8, side=:right)
violin!(ca, alpha=0.8, side=:right)
violin!(fl, alpha=0.8, side=:right)
```

**Expected Outcome:**

![image](https://user-images.githubusercontent.com/7498849/102710776-a1d00380-42da-11eb-889d-1f4d6437ab2e.png)

**Actual Outcome:**

![image](https://user-images.githubusercontent.com/7498849/102710785-bdd3a500-42da-11eb-9115-faf5077f4546.png)

The same goes for the next plot, with the label being the year.

**Expected Outcome:**

![image](https://user-images.githubusercontent.com/7498849/102710814-08edb800-42db-11eb-85bc-58a5a72cc506.png)

**Actual Outcome:**

![image](https://user-images.githubusercontent.com/7498849/102710817-1a36c480-42db-11eb-81eb-a41d23ef1bc4.png)

What am I doing wrong? Can anyone please help?

**Comment by logankilpatrick** [comment]
I also fixed this, thanks again!
