### ISSUE TITLE
Use of DataFrames.by() in video for 01. Data

### ISSUE THREAD

**Issue by blongworth** [JuliaAcademy/DataScience#28]
At around 21:20, `by(D, :StateName, size)` is used to illustrate usefulness of DataFrames. `by` has been removed from DataFrames, so this should be changed to `combine(groupby(D, :StateName), size)` instead. Would also be good to remind novices about `:`.

**Comment by blongworth** [comment]
Same with `join()` in the next section. Has been replaced by `innerjoin()` in the notebook, but not in the video.

**Comment by logankilpatrick** [comment]
This has been updated. Thanks again!

**Comment by adenoz** [comment]
Hey @logankilpatrick I just cloned this repo yesterday and it still has the `by()` section in it. The `join()` has been updated to `innerjoin()` though. But when I browse through the actual notebook here on Github, the `by()` code block doesn't even seem to be there so it looks like it's been removed. And also, `by()` is still mentioned at the bottom in the Finally section.

**Comment by logankilpatrick** [comment]
Hey @adenoz, can you open a PR if you're comfortable fixing these issues?

**Comment by adenoz** [comment]
Let me look into that. That'll be my first PR. I'll look into over next day or two.

**Comment by adenoz** [comment]
Done @logankilpatrick . I realise I had 'by' in my initial code as I was following along with the lessons so wrote it in. I made minor amendments to the Finally... section. See #41
