### ISSUE TITLE
Join( ) function have been replaced for other types of join methods on the first notebook.

### ISSUE THREAD

**Issue by greatti** [JuliaAcademy/DataScience#30]
At the documentation we'll see around 6 or 7 types of join, including crossjoin( ), antijoin( ) and others that i have never heard about, but most of them are like the Python join methods. 
https://dataframes.juliadata.org/stable/lib/functions/#Joining

**Comment by logankilpatrick** [comment]
Thanks for the heads up. I have updated that notebook!
