### ISSUE TITLE
Required Julia version?

### ISSUE THREAD

**Issue by DilumAluthge** [JuliaAcademy/DataScience#35]
What version of Julia is required? The README seems to suggest 1.4, but recent commits imply that 1.6 is required.

**Comment by brenhinkeller** [comment]
For context: some users appear to be getting errors on 1.4: https://stackoverflow.com/questions/68177877/need-help-resolving-typeerror-in-julia

**Comment by brenhinkeller** [comment]
#36 would potentially fix as far as this repo is concerned, though content on JuliaAcademy may also need to be updated to match
