### ISSUE TITLE
'data/face_recog_qr.mat' reffered in '02. Linear Algebra.ipynb' is missing

### ISSUE THREAD

**Issue by LStoleriu** [JuliaAcademy/DataScience#4]
'data/face_recog_qr.mat' reffered in '02. Linear Algebra.ipynb' is missing
Original remark by 'on ButtonUp' here: https://youtu.be/bndXPsRHPg0?t=1823

**Comment by onButtonUp** [comment]
The videos are engaging. It's good to see data science examples using Julia 1.4.1.

)

**Comment by nassarhuda** [comment]
Thanks for bringing it up, this file should be there now.
