### ISSUE TITLE
Data not Found? - Video 1: Data, by Dr. Huda Nassar

### ISSUE THREAD

**Issue by ankit48365** [JuliaAcademy/DataScience#6]
Hi, Please help me understand, there is something i am missing completely, i am running your program on Jupyter notebook.

For all the Import data package (JLD, NPZ, RDATA, MAT), I get the error data not found

File data/mytempdata.jld cannot be found
SystemError: opening file "data/mytempdata.npz": No such file or directory
SystemError: opening file "data/mytempdata.rda": No such file or directory
File "data/mytempdata.mat" does not exist and create was not specified

**Comment by nassarhuda** [comment]
Can you double check that the file `mytempdata.npz`(and all the others) are present in the directory `data`?

**Comment by ankit48365** [comment]
I can see them in data directory, wondering, why jupyter notebook is giving error, but thanks Nassar, you helped me

![image](https://user-images.githubusercontent.com/56010722/83528883-7b618c80-a49e-11ea-9ac4-9502615e7893.png)
