### ISSUE TITLE
MethodError: no method matching streamtypes(::Type{DataFrame})

### ISSUE THREAD

**Issue by ocissor** [JuliaAcademy/DataScience#8]
I am trying to load a CSV file using CSV.read().like CSV.read("data.csv").I get the error. I also tried by giving the full path but still, it doesn't work.

**Comment by nassarhuda** [comment]
I tried to regenerate -- with different alternatives even with the newer julia version and couldn't replicate. Can you show your versioninfo(), and the CSV package version? And is the file you're having trouble with one that is part of this project? If not, and if you have a link to the file also feel free to share it here.

**Comment by ocissor** [comment]
I was initially using version 1.0.5 and when I changed it to 1.4.2 error was gone.

**Comment by nassarhuda** [comment]
Great. will close this issue then.
